import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv("BestMoviesNetflix.csv")
print("\n---- FIRST 5 ROWS ----")
print(data.head())
print("\n----DATA INFO----")
print(data.info())
print("\n----STATISTICS----")
print(data.describe())
print("\n---- MISSING VALUES----")
print(data.isnull().sum())
print("\n----UNIQUE GENRES----")
print(data["MAIN_GENRE"].unique())
genre_count=data["MAIN_GENRE"].value_counts()
print("\n----GENRE COUNT----")
print(genre_count)
genre_count.plot(kind="bar")
plt.title("Genre Distribution")
plt.xlabel("Genre")
plt.ylabel("Count")
plt.show()
country_count=data["MAIN_PRODUCTION"].value_counts()
country_count.plot(kind="bar")
plt.title("Production Country Distribution")
plt.xlabel("Country")
plt.ylabel("Count")
plt.show()
