import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv("BestMoviesNetflix.csv")
print(data.head())
print(data.info())
print(data.describe())
print(data.isnull().sum())
print(data["MAIN_GENRE"].unique())
genre_count=data["MAIN_GENRE"].value_counts()
print(genre_count)
genre_count.plot(kind="bar")
plt.title("Genre Distribution")
plt.xlabel("Genre")
plt.ylabel("Count")
plt.show()
country_count=data["MAIN_PRODUCTION"].value_counts()
country_count.plot(kind="bar")
plt.title("Production Country Distribution")
plt.xlabel("Country")
plt.ylabel("Count")
plt.show()
